/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/albums/': RouteRecordInfo<'/albums/', '/albums', Record<never, never>, Record<never, never>>,
    '/albums/AR': RouteRecordInfo<'/albums/AR', '/albums/AR', Record<never, never>, Record<never, never>>,
    '/albums/Dress': RouteRecordInfo<'/albums/Dress', '/albums/Dress', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/Card-Reader': RouteRecordInfo<'/posts/Card-Reader', '/posts/Card-Reader', Record<never, never>, Record<never, never>>,
    '/posts/LinerSAT-Cal': RouteRecordInfo<'/posts/LinerSAT-Cal', '/posts/LinerSAT-Cal', Record<never, never>, Record<never, never>>,
    '/posts/PlutoSDR-Study-01/': RouteRecordInfo<'/posts/PlutoSDR-Study-01/', '/posts/PlutoSDR-Study-01', Record<never, never>, Record<never, never>>,
    '/posts/PlutoSDR-Study-02/': RouteRecordInfo<'/posts/PlutoSDR-Study-02/', '/posts/PlutoSDR-Study-02', Record<never, never>, Record<never, never>>,
    '/posts/QSL-Manager-PY': RouteRecordInfo<'/posts/QSL-Manager-PY', '/posts/QSL-Manager-PY', Record<never, never>, Record<never, never>>,
    '/posts/QSL-Query': RouteRecordInfo<'/posts/QSL-Query', '/posts/QSL-Query', Record<never, never>, Record<never, never>>,
    '/sponsors/': RouteRecordInfo<'/sponsors/', '/sponsors', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
